apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: airw-pod-reader-binding
  namespace: airw

subjects:
  - kind: ServiceAccount
    name: airw-backend-serviceaccount
    namespace: airw

roleRef:
  kind: Role
  name: airw-pod-reader
  apiGroup: rbac.authorization.k8s.io